// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.API.Infrastructure.Persistance;

#nullable disable

namespace Server.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("registration")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Server.API.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<int>("IndustryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK_Companies");

                    b.HasIndex("IndustryId")
                        .HasDatabaseName("IX_Companies_IndustryId");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Companies_Name");

                    b.ToTable("Companies", "registration");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IndustryId = 1,
                            Name = "Alpha Manufacturing GmbH"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 1, 2, 0, 0, 0, 0, DateTimeKind.Utc),
                            IndustryId = 2,
                            Name = "Beta IT Solutions AG"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 1, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            IndustryId = 3,
                            Name = "MediCare Kliniken GmbH"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 1, 4, 0, 0, 0, 0, DateTimeKind.Utc),
                            IndustryId = 4,
                            Name = "SecureFinance AG"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            IndustryId = 5,
                            Name = "RetailX Handels GmbH"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            IndustryId = 6,
                            Name = "LogiTrans Logistics GmbH"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 1, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            IndustryId = 7,
                            Name = "EduTech Academy GmbH"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            IndustryId = 8,
                            Name = "GreenEnergy Solutions AG"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 1, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            IndustryId = 9,
                            Name = "AutoDrive Systems GmbH"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            IndustryId = 10,
                            Name = "FreshBite Foods GmbH"
                        });
                });

            modelBuilder.Entity("Server.API.Models.Industry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id")
                        .HasName("PK_Industries");

                    b.ToTable("Industries", "registration");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Manufacturing"
                        },
                        new
                        {
                            Id = 2,
                            Name = "IT Services"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Healthcare"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Finance"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Retail"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Logistics"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Education"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Energy"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Automotive"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Food & Beverage"
                        });
                });

            modelBuilder.Entity("Server.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(3)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("PrivacyAcceptedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("TermsAcceptedAt")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_Users");

                    b.HasIndex("CompanyId")
                        .HasDatabaseName("IX_Users_CompanyId");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_UserName");

                    b.ToTable("Users", "registration");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2024, 2, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "michael.keller@example.com",
                            FirstName = "Michael",
                            LastName = "Keller",
                            PasswordHash = new byte[] { 1, 2, 3, 4, 5 },
                            PasswordSalt = new byte[] { 9, 8, 7, 6 },
                            PrivacyAcceptedAt = new DateTime(2024, 2, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            TermsAcceptedAt = new DateTime(2024, 2, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserName = "michael.keller"
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2024, 2, 2, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "sarah.brandt@example.com",
                            FirstName = "Sarah",
                            LastName = "Brandt",
                            PasswordHash = new byte[] { 1, 1, 2, 2, 3 },
                            PasswordSalt = new byte[] { 4, 4, 5, 5 },
                            PrivacyAcceptedAt = new DateTime(2024, 2, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            TermsAcceptedAt = new DateTime(2024, 2, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserName = "sarah.brandt"
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 2,
                            CreatedAt = new DateTime(2024, 2, 3, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "thomas.fischer@example.com",
                            FirstName = "Thomas",
                            LastName = "Fischer",
                            PasswordHash = new byte[] { 5, 4, 3, 2, 1 },
                            PasswordSalt = new byte[] { 1, 2, 3, 4 },
                            PrivacyAcceptedAt = new DateTime(2024, 2, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            TermsAcceptedAt = new DateTime(2024, 2, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserName = "thomas.fischer"
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 3,
                            CreatedAt = new DateTime(2024, 2, 4, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "laura.schmidt@example.com",
                            FirstName = "Laura",
                            LastName = "Schmidt",
                            PasswordHash = new byte[] { 9, 9, 8, 8, 7 },
                            PasswordSalt = new byte[] { 3, 3, 2, 2 },
                            PrivacyAcceptedAt = new DateTime(2024, 2, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            TermsAcceptedAt = new DateTime(2024, 2, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserName = "laura.schmidt"
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = 4,
                            CreatedAt = new DateTime(2024, 2, 5, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "jonas.mueller@example.com",
                            FirstName = "Jonas",
                            LastName = "Müller",
                            PasswordHash = new byte[] { 7, 7, 7, 7, 7 },
                            PasswordSalt = new byte[] { 1, 3, 5, 7 },
                            PrivacyAcceptedAt = new DateTime(2024, 2, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            TermsAcceptedAt = new DateTime(2024, 2, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            UserName = "jonas.mueller"
                        });
                });

            modelBuilder.Entity("Server.API.Models.Company", b =>
                {
                    b.HasOne("Server.API.Models.Industry", "Industry")
                        .WithMany("Companies")
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Companies_Industries");

                    b.Navigation("Industry");
                });

            modelBuilder.Entity("Server.API.Models.User", b =>
                {
                    b.HasOne("Server.API.Models.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Users_Companies");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Server.API.Models.Company", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Server.API.Models.Industry", b =>
                {
                    b.Navigation("Companies");
                });
#pragma warning restore 612, 618
        }
    }
}
